- assets/components/nav/nav.js
- pages/onlinegame/onlinegame.js
- pages/waitgame/waitgame.js
1. 게임 중 페이지 이동 시 5대0으로 상대방 승리 처리
2. 게임 중 페이지 이동 시 웹소켓 연결 종료
3. waitgame, onlinegame 토큰 만료 시 리프레쉬 토큰 사용
> [Feat] 게임 중 페이지 이동 시 웝소켓 연결 종료 리프레쉬 토큰 재발급/#48

- assets/components/nav/nav.js
- pages/2fa/2fa.js
- pages/login/login.js
> fix: 로그인, 2fa 관련 에러 수정

- css/global.css
- js/index.js
- js/pages.js
- pages/main/main.js
- pages/offline_game/offline_game.js
- pages/offlinewaitgame/matchTypeSelect.css
- pages/offlinewaitgame/matchTypeSelect.js
- pages/offlinewaitgame/offlinewaitgame.js
게임 종료 후 alert 버튼 클릭 시 백엔드에 socket으로 알림 기능 추가하여 alert를 눌러야 다음 게임이 진행되도록 했습니다. 이거 확인하시면 백엔드 pull request도 받아주세용. 세트라서.
> Feat/오프라인 게임 페이지 추가

- css/global.css
- js/index.js
- js/pages.js
- pages/main/main.js
- pages/offline_game/offline_game.js
- pages/offlinewaitgame/matchTypeSelect.css
- pages/offlinewaitgame/matchTypeSelect.js
- pages/offlinewaitgame/offlinewaitgame.js
이제 오프라인 게임 순서 : 오프라인 게임버튼 클릭 -> matchType 선택 -> player nickname 입력 -> 게임 시작 순서로 진행됩니다~
> Feat/오프라인 게임 대기방 연결/#58

- Makefile
- assets/components/nav/nav.js
- assets/components/player-info/player-info.js
- docker-compose.yml
- js/token.js
- nginx.conf
- pages/2fa/2fa.js
- pages/42oauth/42oauth.js
- pages/friend/friend.js
- pages/login/login.js
- pages/mypage/mypage.js
- pages/nickname/nickname.js
- pages/offline_game/offline_game.js
- pages/onlinegame/onlinegame.js
- pages/signup/signup.js
- pages/waitgame/waitgame.js
🚨 프론트 디렉토리 이름 front로 변경 필수
프론트 백엔드 현재 위치 상관없이 둘 중 한군데서 make 하시면 됩니당
> feat: docker compose 통합 & api요청 https로 수정

- assets/components/nav/nav.css
- pages/mypage/mypage.css
> Design: nav 랑 마이페이지에서 42프로필 비율 깨지는 거 수정

- assets/components/nav/nav.js
- assets/components/player-info/player-info.js
- js/index.js
- js/token.js
- nginx.conf
- pages/2fa/2fa.js
- pages/42oauth/42oauth.js
- pages/friend/friend.js
- pages/login/login.js
- pages/mypage/mypage.js
- pages/nickname/nickname.js
- pages/offline_game/offline_game.js
- pages/onlinegame/onlinegame.js
- pages/rank/rank.js
- pages/signup/signup.js
- pages/waitgame/waitgame.js
1. 백엔드 .env파일에 SERVER_IP=https://클러맥아이피 ex)SERVER_IP=https://10.11.1.1 추가
2. front/js/index.js 4번째줄 export const SERVER_IP = '172.22.19.47'; 이것도 클러맥아이피로 수정
3. make re
4. 다른 클러맥에서 https://클러맥아이피 접속
5. 온라인 매칭 되는지 확인
> Feat: 온라인 가능한 api로 수정

- js/index.js
- pages/offline_game/offline_game.css
- pages/offline_game/offline_game.js
- pages/offlinewaitgame/offlinewaitgame.js
- pages/onlinegame/onlinegame.css
- pages/onlinegame/onlinegame.js
- pages/waitgame/waitgame.js
게임화면일 때 nav바 숨김 -> 종료 후 메인으로 이동 및 nav바 보이게
- 온라인
- 오프라인
피드백 자유롭게 주세여~ 온라인 게임에 닉네임이랑 스코어 추가하는 건 인규가 해준다고 합니다^^
> Design: 게임화면 디자인

- js/index.js
- pages/friend/friend.js
- 알림 nav에서 받아오도록 수정
- 채팅 소켓 갑자기 잘 됨
> [fix] 친구 페이지 소켓

- assets/components/friend-list/friend-list.js
- assets/components/nav/nav.js
- js/index.js
- pages/friend/friend.js
로그인시 친구 모두에게 메시지를 보내 실시간으로 status 상태 변경되게 변경
알림 컨슈머로 통신하는거라  친구가 로그인, 로그아웃 할때마다 친구페이지에 종모양 알림이 떠서 메세지 type이 "status_message"인거는 알림이 안뜨도록 하면 좋을 것 같은데 그 부분 코드를 못 찾겟어서 일단 냅뒀습니당..
> Feat/온라인오프라인 소켓/#102

- js/index.js
- pages/offline_game/offline_game.js
> [fix]: 오프라인 게임 종료 후 네브 작동 안됨

- assets/components/offline-player-info/offline-player-info.css
- pages/offlinewaitgame/matchTypeSelect.css
- pages/offlinewaitgame/offlinewaitgame.css
- pages/offlinewaitgame/offlinewaitgame.js
- pages/waitgame/waitgame.css
페이지마다 있는 흰색 배경 다른 페이지들과 통일하고 css 조금 수정했습니다
> Design: 게임대기 css 정돈

- pages/onlinegame/onlinegame.css
- pages/onlinegame/onlinegame.js
- pages/waitgame/waitgame.js
- 온라인 매칭 에러 수정
- 온라인 게임 닉네임, 스코어 표시
친구 초대 후 게임 플레이 -> 정상작동 확인 -> 닉네임이랑 스코어 표시 확인
랜덤매칭 게임 플레이 -> 정상작동 확인 -> 닉네임이랑 스코어 표시 확인
> Design: 온라인 매칭 에러 닉네임 스코어 표시/#109

- pages/offline_game/offline_game.css
- pages/offline_game/offline_game.js
- pages/onlinegame/onlinegame.css
- pages/onlinegame/onlinegame.js
> feat: 온/오프라인 조작키 띄우기

- assets/components/nav/nav.js
- pages/waitgame/waitgame.css
- pages/waitgame/waitgame.js
인규가 작업한 거에 디자인 조금 수정했습니다 
다른 브랜치에 푸쉬해버려서 요걸로 머지할게요!
> [Fix] 안내 메시지 수정 - 디자인 반영

- pages/onlinegame/onlinegame.js
- pages/waitgame/waitgame.js
온라인 게임 진행 중 뒤로가기 누르면 패배처리 되는지 확인
> [fix]: 온라인 게임 뒤로가기 패배 처리

- assets/components/chat-room/chat-room.css
- assets/components/friend-list/friend-list.css
- assets/components/friend-request/friend-request.css
- assets/components/friend-request/friend-request.js
- assets/components/user-search-modal/user-search-modal.css
- pages/friend/friend.css
- pages/friend/friend.js
- pages/login/login.css
- pages/mypage/mypage.js
- 친구요청목록에 온오프라인 상태 잘 반영되는지
- 마이페이지에서 닉네임/이미지 변경 시 프로필, 경기기록 모두 업데이트되는지
- 친구페이지 css 피드백
> [Fix] 친구요청목록 상태반영 & css 수정

- assets/components/friend-list/friend-list.css
- assets/components/friend-list/friend-list.js
- pages/friend/friend.js
- 이제 차단함 로딩 잘 됩니다
- 차단해제 누르면 친구함으로 이동됩니다 (친구 박스가..)
> [Fix] 차단함 오류

- pages/waitgame/waitgame.js
> [Fix]: ws 대신 wss 사용

- pages/mypage/mypage.css
- pages/mypage/mypage.js
🚨백엔드 레포 필요🚨
- 마이페이지에서 회원탈퇴하면 로그인 페이지로 이동 확인
- 기존 아이디로 로그인 실패 확인
- 다른 아이디로 들어가서 탈퇴한 아이디 정보 사라졌는지 확인
> [feat]: 회원탈퇴 구현

- assets/components/rank-info/rank-info.css
- pages/42oauth/42oauth.js
- pages/login/login.js
- pages/nickname/nickname.js
- pages/onlinegame/onlinegame.js
- pages/rank/rank.css
- pages/rank/rank.js
- pages/signup/signup.js
- 자체회원가입, 2fa, 42회원가입, 닉네임설정 등 로그인 전반에서 엔터키로 잘 넘어가는지 확인
- 대시보드에 스코어 잘 뜨는지 확인
- 온라인 게임 후에 nav 바 업데이트 잘 되는지 확인(nav 바랑 마이페이지랑 일치하는지)
> [Feat] 로그인 엔터 + 대시보드 스코어 + 온라인 게임 후 nav 업데이트

- assets/components/nav/nav.js
- pages/friend/friend.js
친구페이지가 아닌 페이지에서 친구 요청 or 메세지가 왔을 때 알림 종 잘 뜨는지 확인
친구페이지에서 받은 메세지가 있으면 new 잘 떠있는지 확인
알림 종 떠있을 때 친구페이지 들어가면 사라지는 지 확인
> Feat: 종추가/#148

- assets/components/nav/nav.js
- pages/friend/friend.js
- pages/mypage/mypage.js
> [fix]: 닉네임 변경 후 게임초대 에러 수정

- pages/offline_game/offline_game.css
- pages/offline_game/offline_game.js
토너먼트 첫번째 경기
토너먼트 두번째 경기
토너먼트 세번째 경기는 그대로
> feat : 토너먼트 게임순서 표시

- assets/components/nav/nav.js
- pages/friend/friend.js
- 메세지 보냈을 때 새로운 친구요청 메세지 X
- 친구페이지에 들어와 있을 때 메세지를 받으면 친구 목록에 new 알림 O
- 현재 열려있는 채팅방에 메세지가 왔을 땐 new 알림 X
> Fix: 친구페이지 에러 수정/#154

- pages/friend/friend.js
> Feat: refuse api -> delete api 로 수정
